# Generated by Django 3.2.4 on 2023-05-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_auto_20230509_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
