# Generated by Django 3.2.4 on 2023-05-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_alter_chatuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chatuser',
            managers=[
            ],
        ),
    ]
