# Generated by Django 3.2.4 on 2023-05-08 19:34

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_alter_chatuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chatuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
