# Generated by Django 3.2.4 on 2023-05-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_auto_20230510_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Traveling', 'Traveling'), ('Movie', 'Movie')], max_length=50, null=True),
        ),
    ]
