# Generated by Django 3.2.4 on 2023-05-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_alter_interest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='interests',
            field=models.ManyToManyField(choices=[('sports', 'Sports'), ('music', 'Music'), ('movies', 'Movies'), ('books', 'Books')], to='chat_app.Interest'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
