# Generated by Django 3.2.4 on 2023-05-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0008_auto_20230510_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='interests',
            field=models.ManyToManyField(to='chat_app.Interest'),
        ),
    ]
